ci: environment

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,15 +36,22 @@ jobs:
     - name: Get all environment variables
       id: env
       run: |
-        echo "ENVIRONMENT=dev" >> $GITHUB_ENV
+        echo "infisical_env=dev" >> $GITHUB_ENV
+
         if [ ! "${GITHUB_REF}" == "refs/heads/develop" ]; then
-          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
+          echo "infisical_env=prod" >> $GITHUB_ENV
         fi
+
         curl --request GET \
-          --url "https://us.infisical.com/api/v3/secrets/raw?workspaceId=${{ secrets.INFISICAL_WORKSPACE_ID }}&environment=${{ env.ENVIRONMENT }}" \
+          --url "https://us.infisical.com/api/v3/secrets/raw?workspaceId=${{ secrets.INFISICAL_WORKSPACE_ID }}&environment=${{ env.infisical_env }}" \
           --header 'Authorization: Bearer ${{ env.access_token }}' \
           --header 'Content-Type: application/json' \
           > secrets
+
+        if [ ! -f secrets ]; then
+          echo "Secrets not found"
+          exit 1
+        fi
 
         echo "" > .env
         echo "## GENERATED BY INFISICAL" >> .env
